extends Node

signal hire_developer(developer_index)
signal study_pattern(pattern_index)
signal current_map_event_finished
signal timer_update
signal money_value_changed
signal contract_list_changed(contract_key)
signal developer_panel_update
signal game_start
signal game_finished
